spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instr
    username: instr
    password: instr

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

processing:
  delay:
    ms: 5000
